### PR TITLE
Update Intermediate.txt

### PR DESCRIPTION
**Pull request by ashishbdhane**
Solve 22th Question Using CPP
22. Print all permutation of String both iterative and Recursive way? Used Backtracking in recursion
Used STL function next_permutation() in iterative

### CODE REVIEW

**Comment by ashishbdhane** [comment]
It is not spam, I was the first one to submit Answer of 22nd question Using both Recursion and Iterative Method

**Comment by ashishbdhane** [comment]
Please Verify And Remove Spam tag

**Comment by ashishbdhane** [comment]
Sorry, It Seems by Mistake I deleted solution of 5th Question.
Please Remove SPAM tag

**Comment by ashishbdhane** [comment]
Can you please verify?

**Comment by Gaurav-2803** [comment]
You removed Solution for Q.5

**Pull request merged**
